#pragma once

#define PRELOADCPP_VERSION_MAJOR 26
#define PRELOADCPP_VERSION_MINOR 7
#define PRELOADCPP_VERSION_PATCH 10
#define PRELOADCPP_VERSION_BUILD 0
#define PRELOADCPP_VERSION "26.7.10"
#define PRELOADCPP_COMMIT_HASH "unknown"
